[parity]
base_path = "db.bob"
chain = "../chainspec/tobalaba_local.json"

[ui]
disable = false

[rpc]
disable = false
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
port = 8547
cors = ["*"]

[ipc]
disable = true

[websockets]
disable = true

[dapps]
disable = false

[ipfs]
enable = false

[network]
port = 30304
#node_key = "721d7501b6cbc7f7f3b325607702bf9d6bd467b3"
bootnodes = [
    "enode://170ec31c16bc17cb3d73a29e6ecc14d4fbca35cca6cb7d12726a292aa06b1969a59a4c97090b650eb1c3dfc9fb2c736fbe8310c0323b6b6bf87735860dd1691d@127.0.0.1:30303",
    "enode://47f5f3de6be5d414da5c0962877634f5a144d3d39eaa504fdbfb97f5f43a851e3c29e7a9bd480316485676748c0b3eb30cbb5ae741a19f465a45ce06027e9815@127.0.0.1:30305"
]

[snapshots]
disable_periodic = true

[secretstore]
disable = true

[misc]
logging = "transaction_pool=trace,txqueue=trace,own_tx=trace"
log_file = "./db.bob/parity.log"
color = true

[mining]
engine_signer = "0x78cdc0a56c14aa86f84508f46eb07a27d74b5444"
reseal_on_txs = "none"

# to unlock account of bob
[account]
# unlock = ["0x78cdc0a56c14aa86f84508f46eb07a27d74b5444"]
password = ["bob.pwd"]

[private_tx]
enabled = false
